use super::*;
use crate::crypto::sha256_hmac;
use crate::tls_front::emulator::build_emulated_server_hello;
use crate::tls_front::types::{
    CachedTlsData, ParsedServerHello, TlsBehaviorProfile, TlsProfileSource,
};
use std::time::SystemTime;

/// Build a TLS-handshake-like buffer that contains a valid HMAC digest
/// for the given `secret` and `timestamp`.
///
/// Layout (bytes):
///   [0..TLS_DIGEST_POS]         : fixed filler (0x42)
///   [TLS_DIGEST_POS..+32]       : digest = HMAC XOR [0..0 || timestamp_le]
///   [TLS_DIGEST_POS+32]         : session_id_len = 32
///   [TLS_DIGEST_POS+33..+65]    : session_id filler (0x42)
fn make_valid_tls_handshake_with_session_id(
    secret: &[u8],
    timestamp: u32,
    session_id: &[u8],
) -> Vec<u8> {
    let session_id_len = session_id.len();
    assert!(session_id_len <= u8::MAX as usize);
    let len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1 + session_id_len;
    let mut handshake = vec![0x42u8; len];

    handshake[TLS_DIGEST_POS + TLS_DIGEST_LEN] = session_id_len as u8;
    let sid_start = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1;
    handshake[sid_start..sid_start + session_id_len].copy_from_slice(session_id);
    // Zero the digest slot before computing HMAC (mirrors what validate does).
    handshake[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].fill(0);

    let computed = sha256_hmac(secret, &handshake);

    // digest = HMAC such that XOR with stored digest yields [0..0, timestamp_le].
    // bytes 0-27 of digest == computed[0..28]  -> xored[..28] == 0
    // bytes 28-31 of digest == computed[28..32] XOR timestamp_le
    let mut digest = computed;
    let ts = timestamp.to_le_bytes();
    for i in 0..4 {
        digest[28 + i] ^= ts[i];
    }

    handshake[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].copy_from_slice(&digest);
    handshake
}

fn make_valid_tls_handshake(secret: &[u8], timestamp: u32) -> Vec<u8> {
    make_valid_tls_handshake_with_session_id(secret, timestamp, &[0x42; 32])
}

// ------------------------------------------------------------------
// Happy-path sanity
// ------------------------------------------------------------------

#[test]
fn valid_handshake_with_correct_secret_accepted() {
    let secret = b"correct_horse_battery_staple_32b";
    // timestamp = 0 triggers is_boot_time path, accepted without wall-clock check.
    let handshake = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("alice".to_string(), secret.to_vec())];
    let result = validate_tls_handshake(&handshake, &secrets, true);
    assert!(result.is_some(), "Valid handshake must be accepted");
    assert_eq!(result.unwrap().user, "alice");
}

#[test]
fn deterministic_external_vector_validates_without_helper() {
    // Deterministic vector generated by an external Python stdlib HMAC script,
    // not by this test module helper. This catches mirrored helper mistakes.
    let secret = hex::decode("00112233445566778899aabbccddeeff").unwrap();
    let handshake = hex::decode(
        "4242424242424242424242a93225d1d6b46260bc9ce0cc48c7487d2b1ca5afa7ae9fc6609d9e60a3ca842b204242424242424242424242424242424242424242424242424242424242424242",
    )
    .unwrap();

    let secrets = vec![("vector_user".to_string(), secret)];
    let result = validate_tls_handshake(&handshake, &secrets, true).unwrap();

    assert_eq!(result.user, "vector_user");
    assert_eq!(result.timestamp, 0x01020304);
}

#[test]
fn valid_handshake_timestamp_extracted_correctly() {
    let secret = b"ts_extraction_test";
    let ts: u32 = 0xDEAD_BEEF;
    let handshake = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let result = validate_tls_handshake(&handshake, &secrets, true);
    assert!(result.is_some());
    assert_eq!(result.unwrap().timestamp, ts);
}

// ------------------------------------------------------------------
// HMAC bit-flip rejection - adversarial HMAC forgery attempts
// ------------------------------------------------------------------

/// Flip every single bit across the 28-byte HMAC check window one at a
/// time.  Each flip must cause rejection.  This is the primary guard
/// against a censor gradually narrowing down a valid HMAC via partial
/// matches (which would be exploitable with a variable-time comparison).
#[test]
fn hmac_single_bit_flip_anywhere_in_check_window_rejected() {
    let secret = b"flip_test_secret";
    let base = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // First ensure the unmodified handshake is accepted.
    assert!(
        validate_tls_handshake(&base, &secrets, true).is_some(),
        "Baseline handshake must be accepted before flip tests"
    );

    for byte_pos in 0..28usize {
        for bit in 0u8..8 {
            let mut h = base.clone();
            h[TLS_DIGEST_POS + byte_pos] ^= 1 << bit;
            assert!(
                validate_tls_handshake(&h, &secrets, true).is_none(),
                "Flip of bit {bit} in HMAC byte {byte_pos} must be rejected"
            );
        }
    }
}

/// XOR entire check window (bytes 0-27) with 0xFF - must still fail.
#[test]
fn hmac_full_window_corruption_rejected() {
    let secret = b"full_window_test";
    let mut h = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];
    for i in 0..28 {
        h[TLS_DIGEST_POS + i] ^= 0xFF;
    }
    assert!(validate_tls_handshake(&h, &secrets, true).is_none());
}

/// Byte 27 is the last byte in the checked window.  A non-constant-time
/// `all(|b| b == 0)` that short-circuits on byte 0 would never even reach
/// byte 27, making this an effective "did the fix actually run to the end"
/// sentinel: if this passes but the earlier byte-0 test fails, the check
/// window is not being evaluated end-to-end.
#[test]
fn hmac_last_byte_of_check_window_enforced() {
    let secret = b"last_byte_sentinel";
    let mut h = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];
    // Corrupt only byte 27.
    h[TLS_DIGEST_POS + 27] ^= 0x01;
    assert!(
        validate_tls_handshake(&h, &secrets, true).is_none(),
        "Corruption at byte 27 (end of HMAC window) must cause rejection"
    );
}

// ------------------------------------------------------------------
// User enumeration / multi-user ordering
// ------------------------------------------------------------------

#[test]
fn wrong_user_secret_rejected_even_with_valid_structure() {
    let secret_a = b"secret_alpha";
    let secret_b = b"secret_beta";
    let handshake = make_valid_tls_handshake(secret_b, 0);
    // Only user_a is configured.
    let secrets = vec![("user_a".to_string(), secret_a.to_vec())];
    assert!(
        validate_tls_handshake(&handshake, &secrets, true).is_none(),
        "Handshake for user_b must fail when only user_a is configured"
    );
}

#[test]
fn second_user_in_list_found_when_first_does_not_match() {
    let secret_a = b"secret_alpha";
    let secret_b = b"secret_beta";
    let handshake = make_valid_tls_handshake(secret_b, 0);
    let secrets = vec![
        ("user_a".to_string(), secret_a.to_vec()),
        ("user_b".to_string(), secret_b.to_vec()),
    ];
    let result = validate_tls_handshake(&handshake, &secrets, true);
    assert!(
        result.is_some(),
        "user_b must be found even though user_a comes first"
    );
    assert_eq!(result.unwrap().user, "user_b");
}

#[test]
fn duplicate_secret_keeps_first_user_identity() {
    // If multiple entries share the same secret, the selected identity must
    // stay stable and deterministic (first entry wins).
    let shared = b"same_secret_for_two_users";
    let handshake = make_valid_tls_handshake(shared, 0);
    let secrets = vec![
        ("first_user".to_string(), shared.to_vec()),
        ("second_user".to_string(), shared.to_vec()),
    ];

    let result = validate_tls_handshake(&handshake, &secrets, true);
    assert!(result.is_some());
    assert_eq!(result.unwrap().user, "first_user");
}

#[test]
fn no_user_matches_returns_none() {
    let secret_a = b"aaa";
    let secret_b = b"bbb";
    let secret_c = b"ccc";
    let handshake = make_valid_tls_handshake(b"unknown_secret", 0);
    let secrets = vec![
        ("a".to_string(), secret_a.to_vec()),
        ("b".to_string(), secret_b.to_vec()),
        ("c".to_string(), secret_c.to_vec()),
    ];
    assert!(validate_tls_handshake(&handshake, &secrets, true).is_none());
}

#[test]
fn empty_secrets_list_rejects_everything() {
    let secret = b"test";
    let handshake = make_valid_tls_handshake(secret, 0);
    let secrets: Vec<(String, Vec<u8>)> = Vec::new();
    assert!(validate_tls_handshake(&handshake, &secrets, true).is_none());
}

// ------------------------------------------------------------------
// Timestamp / time-skew boundary attacks
// ------------------------------------------------------------------

#[test]
fn timestamp_at_time_skew_boundaries_accepted() {
    let secret = b"skew_boundary_test_secret";
    let now: i64 = 1_700_000_000;
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // time_diff = now - ts = TIME_SKEW_MIN = -1200
    // -> ts = now - TIME_SKEW_MIN = now + 1200  (20 min in the future).
    let ts_at_future_limit = (now - TIME_SKEW_MIN) as u32;
    let h = make_valid_tls_handshake(secret, ts_at_future_limit);
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, now).is_some(),
        "Timestamp at max-allowed future (time_diff = TIME_SKEW_MIN) must be accepted"
    );

    // time_diff = now - ts = TIME_SKEW_MAX = 600
    // -> ts = now - TIME_SKEW_MAX = now - 600  (10 min in the past).
    let ts_at_past_limit = (now - TIME_SKEW_MAX) as u32;
    let h = make_valid_tls_handshake(secret, ts_at_past_limit);
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, now).is_some(),
        "Timestamp at max-allowed past (time_diff = TIME_SKEW_MAX) must be accepted"
    );
}

#[test]
fn timestamp_one_second_outside_skew_window_rejected() {
    let secret = b"skew_outside_test_secret";
    let now: i64 = 1_700_000_000;
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // time_diff = TIME_SKEW_MAX + 1 = 601  (one second too far in the past)
    // -> ts = now - (TIME_SKEW_MAX + 1) = now - 601
    let ts_too_past = (now - TIME_SKEW_MAX - 1) as u32;
    let h = make_valid_tls_handshake(secret, ts_too_past);
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, now).is_none(),
        "Timestamp one second too far in the past must be rejected"
    );

    // time_diff = TIME_SKEW_MIN - 1 = -1201  (one second too far in the future)
    // -> ts = now - (TIME_SKEW_MIN - 1) = now + 1201
    let ts_too_future = (now - TIME_SKEW_MIN + 1) as u32;
    let h = make_valid_tls_handshake(secret, ts_too_future);
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, now).is_none(),
        "Timestamp one second too far in the future must be rejected"
    );
}

#[test]
fn ignore_time_skew_accepts_far_future_timestamp() {
    let secret = b"ignore_skew_test";
    let now: i64 = 1_700_000_000;
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // 1 hour in the future - outside TIME_SKEW_MAX but should pass with flag.
    let future_ts = (now + 3600) as u32;
    let h = make_valid_tls_handshake(secret, future_ts);
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, true, now).is_some(),
        "ignore_time_skew=true must override window rejection"
    );
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, now).is_none(),
        "ignore_time_skew=false must still reject far-future timestamp"
    );
}

#[test]
fn boot_time_timestamp_accepted_without_ignore_flag() {
    // Timestamps below the boot-time threshold are treated as client uptime,
    // not real wall-clock time.  The proxy allows them regardless of skew.
    let secret = b"boot_time_test";
    // Keep this safely below compatibility cap to assert bypass behavior.
    let boot_ts: u32 = BOOT_TIME_COMPAT_MAX_SECS.saturating_sub(1);
    let handshake = make_valid_tls_handshake(secret, boot_ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];
    assert!(
        validate_tls_handshake(&handshake, &secrets, false).is_some(),
        "Boot-time timestamp must be accepted even with ignore_time_skew=false"
    );
}

// ------------------------------------------------------------------
// Structural / length boundary attacks
// ------------------------------------------------------------------

#[test]
fn too_short_handshake_rejected_without_panic() {
    let secrets = vec![("u".to_string(), b"s".to_vec())];
    // Exactly one byte short of the minimum required length.
    let h = vec![0u8; TLS_DIGEST_POS + TLS_DIGEST_LEN];
    assert!(validate_tls_handshake(&h, &secrets, true).is_none());

    // Empty buffer.
    assert!(validate_tls_handshake(&[], &secrets, true).is_none());
}

#[test]
fn all_prefix_lengths_below_minimum_rejected_without_panic() {
    let min_len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1;
    let secrets = vec![("u".to_string(), b"s".to_vec())];

    for len in 0..min_len {
        let h = vec![0u8; len];
        assert!(
            validate_tls_handshake(&h, &secrets, true).is_none(),
            "prefix length {len} below minimum must be rejected"
        );
    }
}

#[test]
fn claimed_session_id_overflows_buffer_rejected() {
    let session_id_len: usize = 32;
    let min_len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1 + session_id_len;
    let mut h = vec![0u8; min_len];
    // Claim session_id is 33 bytes - one more than the buffer holds.
    h[TLS_DIGEST_POS + TLS_DIGEST_LEN] = (session_id_len + 1) as u8;
    let secrets = vec![("u".to_string(), b"s".to_vec())];
    assert!(validate_tls_handshake(&h, &secrets, true).is_none());
}

#[test]
fn max_session_id_len_255_does_not_panic() {
    // session_id_len = 255 with a buffer that is far too small for it.
    let min_len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1 + 32;
    let mut h = vec![0u8; min_len];
    h[TLS_DIGEST_POS + TLS_DIGEST_LEN] = 255;
    let secrets = vec![("u".to_string(), b"s".to_vec())];
    assert!(validate_tls_handshake(&h, &secrets, true).is_none());
}

#[test]
fn one_byte_session_id_validates_and_is_preserved() {
    let secret = b"sid_len_1_test";
    let handshake = make_valid_tls_handshake_with_session_id(secret, 0, &[0xAB]);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let result = validate_tls_handshake(&handshake, &secrets, true)
        .expect("one-byte session_id handshake must validate");
    assert_eq!(result.session_id, vec![0xAB]);
}

#[test]
fn max_session_id_len_255_with_valid_digest_is_rejected_by_rfc_cap() {
    let secret = b"sid_len_255_test";
    let session_id = vec![0xCCu8; 255];
    let handshake = make_valid_tls_handshake_with_session_id(secret, 0, &session_id);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    assert!(
        validate_tls_handshake(&handshake, &secrets, true).is_none(),
        "legacy_session_id length > 32 must be rejected even with valid digest"
    );
}

// ------------------------------------------------------------------
// Adversarial digest values
// ------------------------------------------------------------------

#[test]
fn all_zeros_digest_rejected() {
    // An all-zeros digest would only pass if HMAC(secret, msg) happens to
    // have its first 28 bytes all zero, which is computationally infeasible.
    let session_id_len: usize = 32;
    let min_len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1 + session_id_len;
    let mut h = vec![0x42u8; min_len];
    h[TLS_DIGEST_POS + TLS_DIGEST_LEN] = session_id_len as u8;
    h[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].fill(0);
    let secrets = vec![("u".to_string(), b"test_secret".to_vec())];
    assert!(validate_tls_handshake(&h, &secrets, true).is_none());
}

#[test]
fn all_ones_digest_rejected() {
    let session_id_len: usize = 32;
    let min_len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1 + session_id_len;
    let mut h = vec![0x42u8; min_len];
    h[TLS_DIGEST_POS + TLS_DIGEST_LEN] = session_id_len as u8;
    h[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].fill(0xFF);
    let secrets = vec![("u".to_string(), b"test_secret".to_vec())];
    assert!(validate_tls_handshake(&h, &secrets, true).is_none());
}

/// Simulate a censor that sends 200 crafted packets with random digests.
/// Every single one must be rejected; no random digest should accidentally
/// pass (probability 2^{-224} per attempt; negligible for 200 trials).
#[test]
fn censor_probe_random_digests_all_rejected() {
    use crate::crypto::SecureRandom;
    let secret = b"production_like_secret_value_xyz";
    let session_id_len: usize = 32;
    let min_len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1 + session_id_len;
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let rng = SecureRandom::new();

    for attempt in 0..200 {
        let mut h = vec![0x42u8; min_len];
        h[TLS_DIGEST_POS + TLS_DIGEST_LEN] = session_id_len as u8;
        let rand_digest = rng.bytes(TLS_DIGEST_LEN);
        h[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].copy_from_slice(&rand_digest);
        assert!(
            validate_tls_handshake(&h, &secrets, true).is_none(),
            "Random digest at attempt {attempt} must not match"
        );
    }
}

/// The check window is bytes 0-27 of the XOR result.  Bytes 28-31 encode
/// the timestamp and must NOT affect whether the HMAC portion validates -
/// only the timestamp range check uses them.  Build a valid handshake with
/// timestamp = 0 (boot-time), flip each of bytes 28-31 with ignore_time_skew
/// enabled, and verify the HMAC portion still passes (the timestamp changes
/// but the proxy still accepts the connection under ignore_time_skew).
#[test]
fn timestamp_bytes_28_31_do_not_affect_hmac_window() {
    let secret = b"window_boundary_test";
    let base = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // Baseline must pass.
    assert!(validate_tls_handshake(&base, &secrets, true).is_some());

    // Flip each of the timestamp bytes; with ignore_time_skew the
    // modified timestamps (small absolute values) still pass boot-time check.
    for i in 28..32usize {
        let mut h = base.clone();
        h[TLS_DIGEST_POS + i] ^= 0xFF;
        // The new timestamp is non-zero but potentially still < boot threshold;
        // use ignore_time_skew=true so wallet test is HMAC-only.
        assert!(
            validate_tls_handshake(&h, &secrets, true).is_some(),
            "Flipping byte {i} (timestamp region) must not invalidate HMAC window"
        );
    }
}

// ------------------------------------------------------------------
// session_id preservation
// ------------------------------------------------------------------

#[test]
fn session_id_is_preserved_verbatim_in_validation_result() {
    // If session_id extraction is ever broken (wrong offset, wrong length,
    // off-by-one), this test will catch it before it silently corrupts the
    // ServerHello that echoes the session_id back to the client.
    let secret = b"session_id_preservation_test";
    let handshake = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let result = validate_tls_handshake(&handshake, &secrets, true).unwrap();

    let sid_len_pos = TLS_DIGEST_POS + TLS_DIGEST_LEN;
    let sid_len = handshake[sid_len_pos] as usize;
    let expected = &handshake[sid_len_pos + 1..sid_len_pos + 1 + sid_len];

    assert_eq!(
        result.session_id, expected,
        "session_id in TlsValidation must be the verbatim bytes from the handshake"
    );
}

// ------------------------------------------------------------------
// Clock decoupling - ignore_time_skew must not consult the system clock
// ------------------------------------------------------------------

/// When `ignore_time_skew = true`, a valid HMAC must be accepted even if
/// `now = 0` (the sentinel used when the clock is not needed).  A broken
/// system clock cannot silently deny service when the admin has explicitly
/// disabled timestamp checking.
#[test]
fn ignore_time_skew_accepts_valid_hmac_with_now_zero() {
    let secret = b"clock_decoupling_test";
    // Use a realistic Unix timestamp that would be far outside the window
    // if compared against now=0 (time_diff would be ~-1_700_000_000).
    let realistic_ts: u32 = 1_700_000_000;
    let h = make_valid_tls_handshake(secret, realistic_ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    assert!(
        validate_tls_handshake_at_time(&h, &secrets, true, 0).is_some(),
        "ignore_time_skew=true must accept a valid HMAC regardless of `now`"
    );

    // Confirm that the same handshake IS rejected when the window is enforced
    // and now=0 (time_diff very negative -> outside window).  This distinguishes
    // "clock decoupling" from "always accept".
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, 0).is_none(),
        "ignore_time_skew=false with now=0 must still reject out-of-window timestamps"
    );
}

/// An HMAC-invalid handshake must be rejected even when ignore_time_skew=true
/// and now=0.  Verifies that the clock-decoupling fix did not weaken HMAC
/// enforcement in the ignore_time_skew path.
#[test]
fn ignore_time_skew_with_now_zero_still_rejects_bad_hmac() {
    let secret = b"clock_no_backdoor_test";
    let mut h = make_valid_tls_handshake(secret, 1_700_000_000);
    let secrets = vec![("u".to_string(), secret.to_vec())];
    // Corrupt the HMAC check window.
    h[TLS_DIGEST_POS] ^= 0xFF;
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, true, 0).is_none(),
        "Broken HMAC must be rejected even with ignore_time_skew=true and now=0"
    );
}

#[test]
fn system_time_before_unix_epoch_is_rejected_without_panic() {
    let before_epoch = UNIX_EPOCH
        .checked_sub(std::time::Duration::from_secs(1))
        .expect("UNIX_EPOCH minus one second must be representable");
    assert!(system_time_to_unix_secs(before_epoch).is_none());
}

/// `i64::MAX` is 9_223_372_036_854_775_807 seconds (~292 billion years CE).
/// Any `SystemTime` whose duration since epoch exceeds `i64::MAX` seconds
/// must return `None` rather than silently wrapping to a large negative
/// timestamp that would corrupt every subsequent time-skew comparison.
#[test]
fn system_time_far_future_overflowing_i64_returns_none() {
    // i64::MAX + 1 seconds past epoch overflows i64 when cast naively with `as`.
    let overflow_secs = u64::try_from(i64::MAX).unwrap() + 1;
    if let Some(far_future) = UNIX_EPOCH.checked_add(std::time::Duration::from_secs(overflow_secs))
    {
        assert!(
            system_time_to_unix_secs(far_future).is_none(),
            "Seconds > i64::MAX must return None, not a wrapped negative timestamp"
        );
    }
    // If the platform cannot represent this SystemTime, the test is vacuously
    // satisfied: `checked_add` returning None means the platform already rejects it.
}

// ------------------------------------------------------------------
// Message canonicalization — HMAC covers every byte of the handshake
// ------------------------------------------------------------------

/// Every byte before TLS_DIGEST_POS is part of the HMAC input (because msg
/// = full handshake with only the digest slot zeroed).  An attacker cannot
/// replay a valid handshake with a modified ClientHello header while keeping
/// the stored digest; each such modification produces a different HMAC.
#[test]
fn pre_digest_bytes_are_hmac_covered() {
    // TLS_DIGEST_POS = 11, so 11 bytes precede the digest.
    let secret = b"pre_digest_coverage_test";
    let base = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    for byte_pos in 0..TLS_DIGEST_POS {
        let mut h = base.clone();
        h[byte_pos] ^= 0x01;
        assert!(
            validate_tls_handshake(&h, &secrets, true).is_none(),
            "Flip in pre-digest byte {byte_pos} must cause HMAC check failure"
        );
    }
}

/// session_id bytes follow the digest in the buffer and are also part of the
/// HMAC input.  Flipping any of them invalidates the stored digest, preventing
/// a censor from capturing a valid session_id and replaying it with a different
/// one while keeping the rest of the packet intact.
#[test]
fn session_id_bytes_are_hmac_covered() {
    let secret = b"session_id_coverage_test";
    let base = make_valid_tls_handshake(secret, 0); // session_id_len = 32
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let sid_start = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1;
    for byte_pos in sid_start..base.len() {
        let mut h = base.clone();
        h[byte_pos] ^= 0x01;
        assert!(
            validate_tls_handshake(&h, &secrets, true).is_none(),
            "Flip in session_id byte at offset {byte_pos} must cause HMAC check failure"
        );
    }
}

/// Appending even one byte to a valid handshake changes the HMAC input (msg
/// includes all bytes) and therefore invalidates the stored digest.  This
/// prevents a length-extension-style modification of the payload.
#[test]
fn appended_trailing_byte_causes_rejection() {
    let secret = b"trailing_byte_test";
    let mut h = make_valid_tls_handshake(secret, 0);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    assert!(
        validate_tls_handshake(&h, &secrets, true).is_some(),
        "baseline"
    );

    h.push(0x00);
    assert!(
        validate_tls_handshake(&h, &secrets, true).is_none(),
        "Appending a trailing byte to a valid handshake must invalidate the HMAC"
    );
}

// ------------------------------------------------------------------
// Zero-length session_id (structural edge case)
// ------------------------------------------------------------------

/// session_id_len = 0 is legal in the TLS spec.  The validator must accept a
/// valid handshake with an empty session_id and return an empty session_id
/// slice without panicking or accessing out-of-bounds memory.
#[test]
fn zero_length_session_id_accepted() {
    let secret = b"zero_sid_test";
    // Buffer: pre-digest | digest | session_id_len=0  (no session_id bytes follow)
    let len = TLS_DIGEST_POS + TLS_DIGEST_LEN + 1;
    let mut handshake = vec![0x42u8; len];
    handshake[TLS_DIGEST_POS + TLS_DIGEST_LEN] = 0; // session_id_len = 0
    handshake[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].fill(0);

    let computed = sha256_hmac(secret, &handshake);
    // timestamp = 0 → ts XOR bytes are all zero → digest = computed unchanged.
    handshake[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN].copy_from_slice(&computed);

    let secrets = vec![("u".to_string(), secret.to_vec())];
    let result = validate_tls_handshake(&handshake, &secrets, true);
    assert!(result.is_some(), "zero-length session_id must be accepted");
    assert!(
        result.unwrap().session_id.is_empty(),
        "session_id field must be empty when session_id_len = 0"
    );
}

// ------------------------------------------------------------------
// Boot-time threshold — exact boundary precision
// ------------------------------------------------------------------

/// timestamp = BOOT_TIME_COMPAT_MAX_SECS - 1 is the last value inside
/// the runtime boot-time compatibility window.
/// is_boot_time = true → skew check is skipped entirely → accepted even
/// when `now` is far from the timestamp.
#[test]
fn timestamp_one_below_boot_threshold_bypasses_skew_check() {
    let secret = b"boot_last_value_test";
    let ts: u32 = BOOT_TIME_COMPAT_MAX_SECS - 1;
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // now = 0 → time_diff would be -86_399_999, way outside [-1200, 600].
    // Boot-time bypass must prevent the skew check from running.
    assert!(
        validate_tls_handshake_at_time(&h, &secrets, false, 0).is_some(),
        "ts=BOOT_TIME_COMPAT_MAX_SECS-1 must bypass skew check regardless of now"
    );
}

/// timestamp = BOOT_TIME_COMPAT_MAX_SECS is the first value outside the
/// runtime boot-time compatibility window.
/// is_boot_time = false → skew check IS applied.  Two sub-cases confirm this:
/// once with now chosen so the skew passes (accepted) and once where it fails.
#[test]
fn timestamp_at_boot_threshold_triggers_skew_check() {
    let secret = b"boot_exact_value_test";
    let ts: u32 = BOOT_TIME_COMPAT_MAX_SECS;
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // now = ts + 50 → time_diff = 50, within [-1200, 600] → accepted.
    let now_valid: i64 = ts as i64 + 50;
    assert!(
        validate_tls_handshake_at_time_with_boot_cap(
            &h,
            &secrets,
            false,
            now_valid,
            BOOT_TIME_COMPAT_MAX_SECS,
        )
        .is_some(),
        "ts=BOOT_TIME_COMPAT_MAX_SECS within skew window must be accepted via skew check"
    );

    // now = -1 → time_diff = -121 at the 120-second threshold, outside window
    // for TIME_SKEW_MIN=-120. If boot-time bypass were wrongly applied this
    // would pass.
    assert!(
        validate_tls_handshake_at_time_with_boot_cap(
            &h,
            &secrets,
            false,
            -1,
            BOOT_TIME_COMPAT_MAX_SECS,
        )
        .is_none(),
        "ts=BOOT_TIME_COMPAT_MAX_SECS far from now must be rejected — no boot-time bypass"
    );
}

#[test]
fn replay_window_cap_disables_boot_bypass_for_old_timestamps() {
    let secret = b"boot_cap_disabled_test";
    let ts: u32 = 900;
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let result = validate_tls_handshake_with_replay_window(&h, &secrets, false, 300);
    assert!(
        result.is_none(),
        "timestamp above replay-window cap must not use boot-time bypass"
    );
}

#[test]
fn replay_window_cap_still_allows_small_boot_timestamp() {
    let secret = b"boot_cap_enabled_test";
    let ts: u32 = BOOT_TIME_COMPAT_MAX_SECS.saturating_sub(1);
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let result = validate_tls_handshake_with_replay_window(&h, &secrets, false, 300);
    assert!(
        result.is_some(),
        "timestamp below replay-window cap must retain boot-time compatibility"
    );
}

#[test]
fn large_replay_window_is_hard_capped_for_boot_compatibility() {
    let secret = b"boot_cap_hard_limit_test";
    let ts: u32 = BOOT_TIME_COMPAT_MAX_SECS + 1;
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let result = validate_tls_handshake_with_replay_window(&h, &secrets, false, u64::MAX);
    assert!(
        result.is_none(),
        "very large replay window must not expand boot-time bypass beyond hard compatibility cap"
    );
}

#[test]
fn ignore_time_skew_explicitly_decouples_from_boot_time_cap() {
    let secret = b"ignore_skew_boot_cap_decouple_test";
    let ts: u32 = 1;
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let cap_zero = validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, true, 0, 0);
    let cap_nonzero = validate_tls_handshake_at_time_with_boot_cap(
        &h,
        &secrets,
        true,
        0,
        BOOT_TIME_COMPAT_MAX_SECS,
    );

    assert!(
        cap_zero.is_some(),
        "ignore_time_skew=true must accept valid HMAC"
    );
    assert!(
        cap_nonzero.is_some(),
        "ignore_time_skew path must not depend on boot-time cap"
    );

    let a = cap_zero.unwrap();
    let b = cap_nonzero.unwrap();
    assert_eq!(a.user, b.user);
    assert_eq!(a.timestamp, b.timestamp);
}

#[test]
fn adversarial_small_boot_timestamp_matrix_rejected_when_boot_cap_forced_zero() {
    let secret = b"boot_cap_zero_matrix_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let now: i64 = 1_700_000_000;

    for ts in 0u32..1024u32 {
        let h = make_valid_tls_handshake(secret, ts);
        let result = validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0);
        assert!(
            result.is_none(),
            "boot cap=0 must reject timestamp {ts} when skew checks are active"
        );
    }
}

#[test]
fn light_fuzz_boot_cap_zero_rejects_small_timestamp_space() {
    let secret = b"boot_cap_zero_fuzz_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let now: i64 = 1_700_000_000;
    let mut s: u64 = 0x9E37_79B9_7F4A_7C15;

    for _ in 0..4096 {
        s ^= s << 7;
        s ^= s >> 9;
        s ^= s << 8;
        let ts = (s as u32) % 2048;

        let h = make_valid_tls_handshake(secret, ts);
        let result = validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0);
        assert!(
            result.is_none(),
            "fuzzed boot-range timestamp {ts} must be rejected when cap=0"
        );
    }
}

#[test]
fn stress_boot_cap_zero_rejection_is_deterministic_under_high_iteration_count() {
    let secret = b"boot_cap_zero_stress_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let now: i64 = 1_700_000_000;

    for i in 0u32..20_000u32 {
        let ts = i % 4096;
        let h = make_valid_tls_handshake(secret, ts);
        let result = validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0);
        assert!(
            result.is_none(),
            "iteration {i}: timestamp {ts} must be rejected with cap=0"
        );
    }
}

#[test]
fn replay_window_one_allows_only_zero_timestamp_boot_bypass() {
    let secret = b"replay_window_one_boot_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let ts0 = make_valid_tls_handshake(secret, 0);
    let ts1 = make_valid_tls_handshake(secret, 1);

    assert!(
        validate_tls_handshake_with_replay_window(&ts0, &secrets, false, 1).is_some(),
        "replay_window=1 must allow timestamp 0 via boot-time compatibility"
    );
    assert!(
        validate_tls_handshake_with_replay_window(&ts1, &secrets, false, 1).is_none(),
        "replay_window=1 must reject timestamp 1 on normal wall-clock systems"
    );
}

#[test]
fn replay_window_two_allows_ts0_ts1_but_rejects_ts2() {
    let secret = b"replay_window_two_boot_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let ts0 = make_valid_tls_handshake(secret, 0);
    let ts1 = make_valid_tls_handshake(secret, 1);
    let ts2 = make_valid_tls_handshake(secret, 2);

    assert!(validate_tls_handshake_with_replay_window(&ts0, &secrets, false, 2).is_some());
    assert!(validate_tls_handshake_with_replay_window(&ts1, &secrets, false, 2).is_some());
    assert!(
        validate_tls_handshake_with_replay_window(&ts2, &secrets, false, 2).is_none(),
        "timestamp equal to replay-window cap must not use boot-time bypass"
    );
}

#[test]
fn adversarial_skew_boundary_matrix_accepts_only_inclusive_window_when_boot_disabled() {
    let secret = b"skew_boundary_matrix_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let now: i64 = 1_700_000_000;

    for offset in -1500i64..=1500i64 {
        let ts_i64 = now - offset;
        let ts = u32::try_from(ts_i64).expect("timestamp must fit u32 for test matrix");
        let h = make_valid_tls_handshake(secret, ts);
        let accepted =
            validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0).is_some();
        let expected = (TIME_SKEW_MIN..=TIME_SKEW_MAX).contains(&offset);
        assert_eq!(
            accepted, expected,
            "offset {offset} must match inclusive skew window when boot bypass is disabled"
        );
    }
}

#[test]
fn light_fuzz_skew_window_rejects_outside_range_when_boot_disabled() {
    let secret = b"skew_outside_fuzz_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let now: i64 = 1_700_000_000;
    let mut s: u64 = 0x0123_4567_89AB_CDEF;

    for _ in 0..4096 {
        s ^= s << 7;
        s ^= s >> 9;
        s ^= s << 8;

        let magnitude = 1300i64 + ((s % 2000u64) as i64);
        let sign = if (s & 1) == 0 { 1i64 } else { -1i64 };
        let offset = sign * magnitude;
        let ts_i64 = now - offset;
        let ts = u32::try_from(ts_i64).expect("timestamp must fit u32 for fuzz test");

        let h = make_valid_tls_handshake(secret, ts);
        let accepted =
            validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0).is_some();
        assert!(
            !accepted,
            "offset {offset} must be rejected outside strict skew window"
        );
    }
}

#[test]
fn stress_boot_disabled_validation_matches_time_diff_oracle() {
    let secret = b"boot_disabled_oracle_stress_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let now: i64 = 1_700_000_000;
    let mut s: u64 = 0xBADC_0FFE_EE11_2233;

    for _ in 0..25_000 {
        s ^= s << 7;
        s ^= s >> 9;
        s ^= s << 8;
        let ts = s as u32;
        let h = make_valid_tls_handshake(secret, ts);

        let accepted =
            validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0).is_some();
        let time_diff = now - i64::from(ts);
        let expected = (TIME_SKEW_MIN..=TIME_SKEW_MAX).contains(&time_diff);
        assert_eq!(
            accepted, expected,
            "boot-disabled validation must match pure time-diff oracle"
        );
    }
}

#[test]
fn integration_large_user_list_with_boot_disabled_finds_only_matching_user() {
    let now: i64 = 1_700_000_000;
    let target_secret = b"target_user_secret";
    let target_ts = (now - 1) as u32;
    let handshake = make_valid_tls_handshake(target_secret, target_ts);

    let mut secrets = Vec::new();
    for i in 0..512u32 {
        secrets.push((
            format!("noise-{i}"),
            format!("noise-secret-{i}").into_bytes(),
        ));
    }
    secrets.push(("target-user".to_string(), target_secret.to_vec()));

    let result = validate_tls_handshake_at_time_with_boot_cap(&handshake, &secrets, false, now, 0)
        .expect("matching user should validate within strict skew window");
    assert_eq!(result.user, "target-user");
}

#[test]
fn light_fuzz_ignore_time_skew_accepts_wide_timestamp_range_with_valid_hmac() {
    let secret = b"ignore_skew_fuzz_accept_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];
    let mut s: u64 = 0xC0FF_EE11_2233_4455;

    for _ in 0..2048 {
        s ^= s << 7;
        s ^= s >> 9;
        s ^= s << 8;
        let ts = s as u32;

        let h = make_valid_tls_handshake(secret, ts);
        let result = validate_tls_handshake_with_replay_window(&h, &secrets, true, 60);
        assert!(
            result.is_some(),
            "ignore_time_skew=true must accept valid HMAC for arbitrary timestamp"
        );
    }
}

#[test]
fn light_fuzz_small_replay_window_rejects_far_timestamps_when_skew_enabled() {
    let secret = b"replay_window_reject_fuzz_test";
    let secrets = vec![("u".to_string(), secret.to_vec())];

    for ts in 300u32..=1323u32 {
        let h = make_valid_tls_handshake(secret, ts);
        let result = validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, 0, 300);
        assert!(
            result.is_none(),
            "with skew checks enabled and boot cap=300, timestamp >=300 at now=0 must be rejected"
        );
    }
}

// ------------------------------------------------------------------
// Extreme timestamp values
// ------------------------------------------------------------------

/// u32::MAX is a valid timestamp value.  When ignore_time_skew=true the HMAC
/// is the only gate, and a correctly constructed handshake must be accepted.
#[test]
fn u32_max_timestamp_accepted_with_ignore_time_skew() {
    let secret = b"u32_max_ts_accept_test";
    let h = make_valid_tls_handshake(secret, u32::MAX);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    let result = validate_tls_handshake(&h, &secrets, true);
    assert!(
        result.is_some(),
        "u32::MAX timestamp must be accepted with ignore_time_skew=true"
    );
    assert_eq!(
        result.unwrap().timestamp,
        u32::MAX,
        "timestamp field must equal u32::MAX verbatim"
    );
}

/// u32::MAX > BOOT_TIME_MAX_SECS so the skew check IS applied when
/// ignore_time_skew=false.  now=u32::MAX so time_diff=0, well within window.
#[test]
fn u32_max_timestamp_rejected_outside_skew_window() {
    let secret = b"u32_max_ts_reject_test";
    let h = make_valid_tls_handshake(secret, u32::MAX);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // now far from u32::MAX → time_diff huge → rejected.
    let result = validate_tls_handshake_at_time(&h, &secrets, false, 0);
    assert!(
        result.is_none(),
        "u32::MAX timestamp must be rejected when now=0 and skew checks are active"
    );
}

#[test]
fn u32_max_minus_one_accepted_within_skew_window() {
    let secret = b"u32_max_minus_one_test";
    let ts = u32::MAX - 1;
    let h = make_valid_tls_handshake(secret, ts);
    let secrets = vec![("u".to_string(), secret.to_vec())];

    // now = ts + 1 → time_diff = 1, within [-1200, 600] → accepted.
    let now = i64::from(ts) + 1;
    let result = validate_tls_handshake_at_time_with_boot_cap(&h, &secrets, false, now, 0);
    assert!(
        result.is_some(),
        "u32::MAX-1 within skew window must be accepted"
    );
}

// ------------------------------------------------------------------
// build_server_hello structural tests
// ------------------------------------------------------------------

fn server_hello_extension_types(response: &[u8]) -> Vec<u16> {
    // ServerHello is the first TLS record (type 0x16).
    // Record: [0x16, ver_hi, ver_lo, len_hi, len_lo, handshake_type(0x02),
    //          body_len(3 bytes), legacy_version(2), random(32),
    //          session_id_len(1), session_id(...), cipher(2), comp(1),
    //          ext_total_len(2), extensions...]
    if response.len() < 5 {
        return Vec::new();
    }
    let record_len = u16::from_be_bytes([response[3], response[4]]) as usize;
    if response.len() < 5 + record_len {
        return Vec::new();
    }
    // Skip handshake type + 3-byte body len + legacy_version + random
    let mut pos = 5 + 1 + 3 + 2 + 32;
    if pos >= response.len() {
        return Vec::new();
    }
    let sid_len = response[pos] as usize;
    pos += 1 + sid_len;
    pos += 2 + 1; // cipher suite + compression
    if pos + 2 > response.len() {
        return Vec::new();
    }
    let ext_total = u16::from_be_bytes([response[pos], response[pos + 1]]) as usize;
    pos += 2;
    let ext_end = pos + ext_total;
    if ext_end > response.len() {
        return Vec::new();
    }
    let mut types = Vec::new();
    while pos + 4 <= ext_end {
        let etype = u16::from_be_bytes([response[pos], response[pos + 1]]);
        let elen = u16::from_be_bytes([response[pos + 2], response[pos + 3]]) as usize;
        types.push(etype);
        pos += 4 + elen;
    }
    types
}

#[test]
fn build_server_hello_never_places_alpn_in_server_hello_extensions() {
    // ALPN must go into the EncryptedExtensions ApplicationData record,
    // NOT into the ServerHello extensions block.  A real TLS 1.3 ServerHello
    // does not contain an ALPN extension; placing one there would be a
    // protocol-level fingerprint.
    let secret = b"alpn_placement_test";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        Some(b"h2".to_vec()),
        0,
        None,
    );
    let exts = server_hello_extension_types(&response);
    assert!(
        !exts.contains(&0x0010),
        "ALPN extension must not appear in ServerHello"
    );
}

#[test]
fn test_build_server_hello_structure() {
    let secret = b"test_secret";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        2048,
        &rng,
        None,
        0,
        None,
    );

    // Response should not be empty
    assert!(!response.is_empty());

    // First record should be ServerHello (TLS handshake = 0x16)
    assert_eq!(response[0], TLS_RECORD_HANDSHAKE);

    // Should have TLS version
    assert_eq!(response[1..3], TLS_VERSION);
}

#[test]
fn test_build_server_hello_digest() {
    let secret = b"test_secret";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    let response1 = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        None,
        0,
        None,
    );
    let response2 = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        None,
        0,
        None,
    );

    // Responses should differ (random padding)
    // But both should be non-empty and valid structure
    assert!(!response1.is_empty());
    assert!(!response2.is_empty());
}

#[test]
fn test_build_server_hello_session_id_echoed() {
    let secret = b"session_echo_test";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xDE, 0xAD, 0xBE, 0xEF];
    let rng = crate::crypto::SecureRandom::new();

    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        None,
        0,
        None,
    );

    assert!(!response.is_empty(), "response must not be empty");

    // ServerHello record starts at byte 0.
    // [0x16, ver_hi, ver_lo, len_hi, len_lo] = 5 bytes header
    // Then handshake message: [0x02, body_len_3bytes, legacy_ver_2, random_32, sid_len_1, sid...]
    // random field starts at offset 5 + 1 + 3 + 2 = 11
    // session_id_len is at 5 + 1 + 3 + 2 + 32 = 43
    let sid_len_pos = 43;
    assert!(
        response.len() > sid_len_pos + 1,
        "response too short to contain session_id"
    );
    let sid_len = response[sid_len_pos] as usize;
    assert_eq!(
        sid_len,
        session_id.len(),
        "session_id length must be echoed"
    );
    assert_eq!(
        &response[sid_len_pos + 1..sid_len_pos + 1 + sid_len],
        session_id.as_slice(),
        "session_id bytes must be echoed verbatim"
    );
}

#[test]
fn test_build_server_hello_with_alpn() {
    let secret = b"alpn_test_secret";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    // Test with h2 ALPN
    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        Some(b"h2".to_vec()),
        0,
        None,
    );
    assert!(!response.is_empty());
    assert_eq!(response[0], TLS_RECORD_HANDSHAKE);
}

#[test]
fn test_build_server_hello_digest_position() {
    // Verify that the HMAC digest is embedded at TLS_DIGEST_POS in the response
    let secret = b"digest_position_test";
    let client_digest = [0xCC; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        None,
        0,
        None,
    );

    // The response digest is placed starting at TLS_DIGEST_POS (byte 11).
    assert!(
        response.len() > TLS_DIGEST_POS + TLS_DIGEST_LEN,
        "Response must be large enough to contain digest"
    );

    // The digest at TLS_DIGEST_POS should not be all zeros (it's the HMAC)
    let digest_bytes = &response[TLS_DIGEST_POS..TLS_DIGEST_POS + TLS_DIGEST_LEN];
    assert!(
        digest_bytes.iter().any(|&b| b != 0),
        "HMAC digest must not be all zeros"
    );
}

// ------------------------------------------------------------------
// new_session_tickets structural tests
// ------------------------------------------------------------------

#[test]
fn new_session_tickets_zero_produces_three_app_records() {
    let secret = b"tickets_zero_test";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        None,
        0,
        None,
    );

    let mut pos = 0usize;
    let mut app_records = 0usize;
    while pos + 5 <= response.len() {
        let rtype = response[pos];
        let rlen = u16::from_be_bytes([response[pos + 3], response[pos + 4]]) as usize;
        let next = pos + 5 + rlen;
        assert!(
            next <= response.len(),
            "TLS record must stay inside response bounds"
        );
        if rtype == TLS_RECORD_APPLICATION {
            app_records += 1;
        }
        pos = next;
    }
    assert_eq!(
        app_records, 3,
        "zero tickets: exactly 3 ApplicationData records expected"
    );
}

#[test]
fn new_session_tickets_one_produces_four_app_records() {
    let secret = b"tickets_one_test";
    let client_digest = [0u8; TLS_DIGEST_LEN];
    let session_id = vec![0xAB; 32];
    let rng = crate::crypto::SecureRandom::new();

    let response = build_server_hello(
        secret,
        &client_digest,
        &session_id,
        1024,
        &rng,
        None,
        1,
        None,
    );

    let mut pos = 0usize;
    let mut app_records = 0usize;
    while pos + 5 <= response.len() {
        let rtype = response[pos];
        let rlen = u16::from_be_bytes([response[pos + 3], response[pos + 4]]) as usize;
        let next = pos + 5 + rlen;
        assert!(next <= response.len())